name: Konto stworzone przez kingakisielinska
title: Documentation on using Visual Studio Code
description: Technologies of Technical Communication classes,  a postgraduate studies at Vistula University
remote_theme: kingakisielinska/just-the-docs

color_scheme: light 


aux_links:
  "Source repository on GitHub":
    - "//github.com/kingakisielinska/kingakisielinska.github.io"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is part of the reference materials for the Technical Communication course at Vistula University (Warsaw)."